In [1]:
import numpy as np

In [2]:
freq = np.arange(10)
freq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.reshape(freq, (5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
values = np.random.rand(10)
values

array([0.67392036, 0.04774957, 0.79839799, 0.08751681, 0.92440052,
       0.19361403, 0.13016206, 0.45145004, 0.28945575, 0.75767221])

In [7]:
np.reshape(values, (2, 5))

array([[0.67392036, 0.04774957, 0.79839799, 0.08751681, 0.92440052],
       [0.19361403, 0.13016206, 0.45145004, 0.28945575, 0.75767221]])

In [8]:
np_array_2d = np.arange(0, 6).reshape((2,3))
np_array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# Sum with axis = 0
np.sum(np_array_2d, axis=0)

array([3, 5, 7])

In [10]:
# Sum with axis = 1
np.sum(np_array_2d, axis=1)

array([ 3, 12])

In [11]:
values

array([0.67392036, 0.04774957, 0.79839799, 0.08751681, 0.92440052,
       0.19361403, 0.13016206, 0.45145004, 0.28945575, 0.75767221])

In [12]:
values.max()

0.9244005246697935

In [13]:
values.argmax()

4

In [14]:
values.min()

0.04774956735373603

In [15]:
values.argmin()

1

In [16]:
values

array([0.67392036, 0.04774957, 0.79839799, 0.08751681, 0.92440052,
       0.19361403, 0.13016206, 0.45145004, 0.28945575, 0.75767221])

In [17]:
values[0]

0.6739203556016369

In [18]:
values[-1]

0.7576722097479865

In [19]:
values[1:3]

array([0.04774957, 0.79839799])

In [20]:
values[3:8]

array([0.08751681, 0.92440052, 0.19361403, 0.13016206, 0.45145004])

In [21]:
num_list = list(range(11))
num_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [22]:
type(num_list)

list

In [23]:
list_slice = num_list[:4]
list_slice

[0, 1, 2, 3]

In [26]:
list_slice[:] = [5, 7, 9, 3]
list_slice

[5, 7, 9, 3]

In [27]:
num_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
num_array = np.arange(11)

In [29]:
num_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
type(num_array)

numpy.ndarray

In [31]:
array_slice = num_array[:4]
array_slice

array([0, 1, 2, 3])

In [32]:
array_slice[:] = [5, 7, 9, 3]
array_slice

array([5, 7, 9, 3])

In [33]:
num_array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
num_array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
array_copy = num_array.copy()[:4]
array_copy

array([5, 7, 9, 3])

In [38]:
num_array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
array_copy[:] = [1, 1, 1, 1]
array_copy

array([1, 1, 1, 1])

In [40]:
num_array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
matrix = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
matrix[1]

array([20, 25, 30])

In [43]:
matrix[2][0]

35

In [45]:
matrix[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [46]:
matrix[2][2]

45

In [47]:
matrix[2, 2]

45

In [48]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
colum_slice = matrix[:, 1:3]
colum_slice

array([[10, 15],
       [25, 30],
       [40, 45]])

In [51]:
even_array = np.arange(0, 20, 2)
even_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
bool_array = even_array > 11
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [53]:
useful_array = even_array[bool_array]
useful_array

array([12, 14, 16, 18])

In [54]:
compact_array = even_array[even_array > 11]
compact_array

array([12, 14, 16, 18])

In [55]:
array1 = np.arange(10).reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
array2 = np.random.rand(10).reshape(2, 5)
array2

array([[0.34928889, 0.99772181, 0.2642809 , 0.39890028, 0.04669609],
       [0.61819998, 0.04693454, 0.77322342, 0.68128144, 0.4998125 ]])

In [57]:
#Addition
array_sum = array1 + array2
array_sum

array([[0.34928889, 1.99772181, 2.2642809 , 3.39890028, 4.04669609],
       [5.61819998, 6.04693454, 7.77322342, 8.68128144, 9.4998125 ]])

In [58]:
#Substraction
array_minus = array1 - array2
array_minus

array([[-3.49288890e-01,  2.27819078e-03,  1.73571910e+00,
         2.60109972e+00,  3.95330391e+00],
       [ 4.38180002e+00,  5.95306546e+00,  6.22677658e+00,
         7.31871856e+00,  8.50018750e+00]])

In [59]:
array_product = array1 * array2
array_product

array([[0.        , 0.99772181, 0.52856179, 1.19670084, 0.18678437],
       [3.09099989, 0.28160723, 5.41256393, 5.45025151, 4.49831253]])

In [60]:
# Division
array_divide = array1 / array2
array_divide

array([[  0.        ,   1.00228339,   7.5677055 ,   7.52067659,
         85.66027102],
       [  8.08799771, 127.837629  ,   9.05301085,  11.74257736,
         18.00675242]])

In [61]:
new_array = np.arange(0, 11)
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
scalar = 100

In [63]:
add_array = new_array + scalar
add_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [64]:
minus_array = add_array - new_array
minus_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [65]:
multi_array = new_array * scalar
multi_array

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [66]:
err_array = new_array / new_array
err_array

C:\Users\duoch\AppData\Local\Temp\ipykernel_27444\3524559128.py:1: RuntimeWarning: invalid value encountered in divide
  err_array = new_array / new_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [67]:
u_add = np.add(new_array, scalar)
u_add

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [68]:
u_sub = np.subtract(add_array, new_array)
u_sub

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [69]:
u_log = np.log(new_array)
u_log

C:\Users\duoch\AppData\Local\Temp\ipykernel_27444\301786795.py:1: RuntimeWarning: divide by zero encountered in log
  u_log = np.log(new_array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [71]:
u_sine = np.sin(new_array)
u_sine

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [72]:
new_array.max()

10

In [73]:
np.max(new_array)

10

In [74]:
my_array = np.array(["Red", "Green", "Orange"])
my_array

array(['Red', 'Green', 'Orange'], dtype='<U6')

In [77]:
extended = np.append(my_array, ["Yellow", "Pink"])
extended

array(['Red', 'Green', 'Orange', 'Yellow', 'Pink'], dtype='<U6')

In [76]:
my_array

array(['Red', 'Green', 'Orange'], dtype='<U6')

In [78]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
extended = np.append(zeros_array, [[1], [2], [3]], axis=1)
extended

array([[0., 0., 0., 1.],
       [0., 0., 0., 2.],
       [0., 0., 0., 3.]])

In [83]:
my_array

array(['Red', 'Green', 'Orange'], dtype='<U6')

In [84]:
updated_array = np.delete(my_array, 1)
updated_array

array(['Red', 'Orange'], dtype='<U6')

In [85]:
my_array

array(['Red', 'Green', 'Orange'], dtype='<U6')

In [86]:
integer_random = np.random.randint(1, 11, size=(4,5))
integer_random

array([[10,  2,  4,  3,  9],
       [ 6,  8,  6,  2,  6],
       [ 5, 10,  4,  3,  3],
       [10,  8,  2,  1,  7]])

In [87]:
updated_array = np.delete(integer_random, 1, axis=0)
updated_array

array([[10,  2,  4,  3,  9],
       [ 5, 10,  4,  3,  3],
       [10,  8,  2,  1,  7]])

In [89]:
integer_random

array([[10,  2,  4,  3,  9],
       [ 6,  8,  6,  2,  6],
       [ 5, 10,  4,  3,  3],
       [10,  8,  2,  1,  7]])

In [90]:
update_array = np.delete(integer_random, 1, axis=1)
update_array

array([[10,  4,  3,  9],
       [ 6,  6,  2,  6],
       [ 5,  4,  3,  3],
       [10,  2,  1,  7]])

In [91]:
my_array = np.random.randint(1, 20, 10)
my_array

array([11,  4,  8,  8, 12, 14,  5,  2, 15,  9])

In [92]:
sorted_array = np.sort(my_array)
sorted_array

array([ 2,  4,  5,  8,  8,  9, 11, 12, 14, 15])

In [93]:
my_array = np.array(["Red", "Green", "Blue", "Yellow"])
my_array

array(['Red', 'Green', 'Blue', 'Yellow'], dtype='<U6')

In [94]:
sorted_array = np.sort(my_array)
sorted_array

array(['Blue', 'Green', 'Red', 'Yellow'], dtype='<U6')

In [95]:
my_array = np.array([False, True, True, False, False, True, False, True])
my_array

array([False,  True,  True, False, False,  True, False,  True])

In [96]:
sorted_array = np.sort(my_array)
sorted_array

array([False, False, False, False,  True,  True,  True,  True])

In [98]:
my_array = np.random.randint(1, 20, size=(4, 6))
my_array

array([[11,  6,  6, 10,  2, 10],
       [ 4,  7, 19,  2,  8, 19],
       [17, 14, 11,  3,  4,  9],
       [10,  4,  8, 14,  7,  6]])

In [99]:
sorted_array = np.sort(my_array)
sorted_array

array([[ 2,  6,  6, 10, 10, 11],
       [ 2,  4,  7,  8, 19, 19],
       [ 3,  4,  9, 11, 14, 17],
       [ 4,  6,  7,  8, 10, 14]])

In [100]:
my_array = np.random.randint(1, 20, 10)
my_array

array([10,  9,  2, 19, 10, 19,  6, 18, 10, 12])

In [101]:
sorted_array = np.sort(my_array)
sorted_array

array([ 2,  6,  9, 10, 10, 10, 12, 18, 19, 19])

In [102]:
reverse_sorted = np.flipud(sorted_array)
reverse_sorted

array([19, 19, 18, 12, 10, 10, 10,  9,  6,  2])

In [103]:
two_d_array = np.random.randint(1, 20, size=(4,6))
two_d_array

array([[14, 10, 11,  6, 18,  2],
       [10, 12, 14, 11,  9, 11],
       [16, 18, 10,  4, 18,  7],
       [16, 19,  5,  9,  8,  3]])

In [104]:
one_d_array = two_d_array.reshape(24)
one_d_array

array([14, 10, 11,  6, 18,  2, 10, 12, 14, 11,  9, 11, 16, 18, 10,  4, 18,
        7, 16, 19,  5,  9,  8,  3])

In [105]:
two_d_array

array([[14, 10, 11,  6, 18,  2],
       [10, 12, 14, 11,  9, 11],
       [16, 18, 10,  4, 18,  7],
       [16, 19,  5,  9,  8,  3]])

In [106]:
one_d_array = two_d_array.reshape(-1)
one_d_array

array([14, 10, 11,  6, 18,  2, 10, 12, 14, 11,  9, 11, 16, 18, 10,  4, 18,
        7, 16, 19,  5,  9,  8,  3])

In [107]:
array1 = np.array([14, 25, 31])
array2 = np.array([10])
result = array1 + array2
result

array([24, 35, 41])

In [108]:
array1 = np.array([10, 12, 14, 16, 18, 20])
array1

array([10, 12, 14, 16, 18, 20])

In [110]:
np.save(r"c:\temp\my_array.npy", array1)

In [111]:
loaded_array = np.load(r"c:\temp\my_array.npy")
loaded_array

array([10, 12, 14, 16, 18, 20])

In [112]:
np.savetxt(r"c:\temp\my_array.txt", array1)

In [113]:
loaded_array = np.loadtxt(r"c:\temp\my_array.txt")
loaded_array

array([10., 12., 14., 16., 18., 20.])

In [114]:
my_array = np.array([2,4,8,10, 12])
my_array

array([ 2,  4,  8, 10, 12])

In [115]:
np.mean(my_array)

7.2

In [116]:
my_array = np.random.randint(1, 20, size=(2,3))
my_array

array([[11, 18, 11],
       [ 1, 19, 17]])

In [117]:
np.mean(my_array, axis=1)

array([13.33333333, 12.33333333])

In [118]:
np.mean(my_array, axis=0)

array([ 6. , 18.5, 14. ])

In [119]:
my_array

array([[11, 18, 11],
       [ 1, 19, 17]])

In [120]:
my_array = np.array([2,4,8, 10, 12])
my_array

array([ 2,  4,  8, 10, 12])

In [121]:
np.median(my_array)

8.0

In [122]:
my_array = np.random.randint(1,20, size=(3,4))
my_array

array([[ 9, 11, 18, 14],
       [13, 11,  4, 17],
       [ 8,  4, 18,  5]])

In [123]:
np.amax(my_array, axis=1)

array([18, 17, 18])

In [124]:
np.amax(my_array, axis=0)

array([13, 11, 18, 17])

In [125]:
my_array = np.array([2,4,8, 10, 12])
my_array

array([ 2,  4,  8, 10, 12])

In [126]:
np.std(my_array)

3.7094473981982814

In [127]:
my_array = np.array([5,8,7, 5, 9, 3, 7, 7, 1, 1, 8, 4, 6, 9, 7, 3])
unique_items = np.unique(my_array)
unique_items

array([1, 3, 4, 5, 6, 7, 8, 9])

In [128]:
my_array

array([5, 8, 7, 5, 9, 3, 7, 7, 1, 1, 8, 4, 6, 9, 7, 3])

In [129]:
unique_items, counts = np.unique(my_array, return_counts=True)
unique_items

array([1, 3, 4, 5, 6, 7, 8, 9])

In [130]:
counts

array([2, 2, 1, 2, 1, 4, 2, 2], dtype=int64)

In [131]:
frequencies = np.asarray((unique_items, counts))
frequencies

array([[1, 3, 4, 5, 6, 7, 8, 9],
       [2, 2, 1, 2, 1, 4, 2, 2]], dtype=int64)

In [132]:
my_array = np.random.randint(1, 20, 10)
my_array

array([ 2,  1,  8,  6, 12,  5, 16,  2,  3,  3])

In [134]:
reversed_array = np.flipud(my_array)
reversed_array

array([ 3,  3,  2, 16,  5, 12,  6,  8,  1,  2])

In [135]:
my_array = np.random.randint(1, 20, size=(3,4))
my_array

array([[11, 12,  5, 18],
       [ 4,  6,  4,  9],
       [ 6, 11,  4,  7]])

In [136]:
reversed_array = np.fliplr(my_array)
reversed_array

array([[18,  5, 12, 11],
       [ 9,  4,  6,  4],
       [ 7,  4, 11,  6]])