In [1]:
# Import NumPy package
import numpy as np

In [2]:
# Create an array
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
# Make a copy of array
y = np.copy(x)
y

array([1, 2, 3])

In [4]:
# Make a deep copy of array
z = x.copy()
z

array([1, 2, 3])

In [5]:
# Create a 2D array
np_array_2d = np.arange(0,6).reshape([2,3])
np_array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
# Sum with axis = 0
np.sum(np_array_2d, axis=0)

array([3, 5, 7])

In [7]:
# Sum with axis = 1
np.sum(np_array_2d, axis=1)

array([ 3, 12])

In [11]:
# Create an array for sorting
s = np.array([[1,4],[3,1]])
s

array([[1, 4],
       [3, 1]])

In [12]:
# Sort along the last axis
np.sort(s)

array([[1, 4],
       [1, 3]])

In [14]:
# Sort along the first axis
np.sort(s, axis=0)

array([[1, 1],
       [3, 4]])

In [16]:
# Sort the flattened array
np.sort(s, axis=None)

array([1, 1, 3, 4])

In [18]:
# Display array x
x

array([1, 2, 3])

In [23]:
# Append data to array x
app=np.append(x, [4,5,6])
app

array([1, 2, 3, 4, 5, 6])

In [26]:
# Insert data into array x
ins = np.insert(x, 1, 9)
ins

array([1, 9, 2, 3])

In [3]:
# Create an array for resize
r = np.array([[0,1],[2,3]])
r

array([[0, 1],
       [2, 3]])

In [6]:
# Resize the array
np.resize(r,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [29]:
# Create an array for delete
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [31]:
# Create one array for concatenate
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [32]:
# Create another array for concatenate
a2 = np.array([[5,6]])
a2

array([[5, 6]])

In [34]:
# Concatenate two arrays on axis 0
np.concatenate((a1,a2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
# Concatenate two arrays on axis 1
np.concatenate((a1,a2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [37]:
# Apply vstack on two arrays
v1 = np.array([1,2,3])
v2 = np.array([2,3,4])
np.vstack((v1,v2))

array([[1, 2, 3],
       [2, 3, 4]])

In [42]:
# Apply vstack on two arrays
t1 = np.array([[1],[2],[3]])
t2 = np.array([[2],[3],[4]])
np.vstack((t1,t2))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [47]:
# Apply hstack with two arrays
np.hstack((v1,v2))

array([1, 2, 3, 2, 3, 4])

In [57]:
# Apply split on an array
sp = np.arange(9)
np.split(sp, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [58]:
# Apply array_split on an array
st = np.arange(7)
np.array_split(st,3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [59]:
# Create an array for hsplit
h = np.arange(16).reshape(4,4)
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
# Apply hsplit on an array
np.hsplit(h, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [61]:
# Create an array for flatten
f = np.array([[1,2],[3,4]])
f

array([[1, 2],
       [3, 4]])

In [62]:
# Apply flatten on an array
f.flatten()

array([1, 2, 3, 4])

In [63]:
# Create an array for transpose
tr = np.arange(4).reshape((2,2))
tr

array([[0, 1],
       [2, 3]])

In [64]:
# Apply transpose on an array
np.transpose(tr)

array([[0, 2],
       [1, 3]])

In [68]:
# Create an array for inv
inv = np.array([[1,2],[3,4]])
inv

array([[1, 2],
       [3, 4]])

In [69]:
# Apply inv on an array
ainv = np.linalg.inv(inv)
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [72]:
# Apply add on two arrays
x1 = np.arange(9).reshape((3,3))
x2 = np.arange(3)
np.add(x1, x2)

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [73]:
# Apply substract on two arrays
np.subtract(x1,x2)

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [74]:
# Apply divide on two arrays
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]
out = np.divide(arr1, arr2)
out

array([ 1.        ,  9.        ,  0.5       ,  4.2       ,  3.83333333])

In [75]:
# Apply multiple on two arrays
res = np.multiply(arr1, arr2)
res

array([  4,  81,   8, 105, 138])

In [76]:
# Apply sqrt on array
np.sqrt(arr1)

array([ 1.41421356,  5.19615242,  1.41421356,  4.58257569,  4.79583152])

In [77]:
# Apply sin on array
np.sin(arr1)

array([ 0.90929743,  0.95637593,  0.90929743,  0.83665564, -0.8462204 ])

In [78]:
# Apply cos on array
np.cos(arr1)

array([-0.41614684, -0.29213881, -0.41614684, -0.54772926, -0.53283302])

In [79]:
# Apply log on array
np.log(arr1)

array([ 0.69314718,  3.29583687,  0.69314718,  3.04452244,  3.13549422])

In [80]:
# Apply dot two arrays
res = np.dot(arr1, arr2)
res

336

In [81]:
# Apply roots on array
np.roots([1,0,-4])

array([ 2., -2.])

In [83]:
# Apply mena on array
m = np.array([1,2,3,4])
np.mean(m)

2.5

In [84]:
# Apply median on array
np.median(m)

2.5

In [85]:
# Apply corrcoef on array
np.corrcoef(m)

1.0

In [86]:
# Apply std on array
np.std(m)

1.1180339887498949

In [88]:
# Use sum on array
m.sum()

10

In [89]:
# Use min on array
m.min()

1

In [90]:
# use max on array
m.max()

4

In [91]:
# use cumsum on array
m.cumsum()

array([ 1,  3,  6, 10], dtype=int32)