In [1]:
# Import NumPy package
import numpy as np

In [2]:
# Create an array
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
# Make a copy of array
y = np.copy(x)
y

array([1, 2, 3])

In [4]:
# Make a deep copy of array
z = x.copy()
z

array([1, 2, 3])

In [5]:
# Create a 2D array
np_array_2d = np.arange(0,6).reshape([2,3])
np_array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
# Sum with axis = 0
np.sum(np_array_2d, axis=0)

array([3, 5, 7])

In [7]:
# Sum with axis = 1
np.sum(np_array_2d, axis=1)

array([ 3, 12])

In [11]:
# Create an array for sorting
s = np.array([[1,4],[3,1]])
s

array([[1, 4],
       [3, 1]])

In [12]:
# Sort along the last axis
np.sort(s)

array([[1, 4],
       [1, 3]])

In [14]:
# Sort along the first axis
np.sort(s, axis=0)

array([[1, 1],
       [3, 4]])

In [16]:
# Sort the flattened array
np.sort(s, axis=None)

array([1, 1, 3, 4])

In [18]:
# Display array x
x

array([1, 2, 3])

In [23]:
# Append data to array x
app=np.append(x, [4,5,6])
app

array([1, 2, 3, 4, 5, 6])

In [26]:
# Insert data into array x
ins = np.insert(x, 1, 9)
ins

array([1, 9, 2, 3])

In [27]:
# Create an array for resize
r = np.array([[0,1],[2,3]])
r

array([[0, 1],
       [2, 3]])

In [28]:
# Resize the array
np.resize(r,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [29]:
# Create an array for delete
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [31]:
# Create one array for concatenate
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [32]:
# Create another array for concatenate
a2 = np.array([[5,6]])
a2

array([[5, 6]])

In [34]:
# Concatenate two arrays on axis 0
np.concatenate((a1,a2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
# Concatenate two arrays on axis 1
np.concatenate((a1,a2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])