In [1]:
# Import Numpy library
import numpy as np

In [8]:
# Print numpy version
np.__version__

'1.16.5'

In [9]:
# Get help on the add function
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
# Create an array with 1, 2, 3, 4
x = np.array([1, 2, 3, 4])

In [7]:
# Test if none of the elements in the array is zero
np.all(x)

True

In [10]:
# Create an array with 0, 1, 2, 3
x = np.array([0, 1, 2, 3])

In [11]:
# Test if none of the elements in the array is zero
np.all(x)

False

In [12]:
# Create an array with 1, 0, 0, 0
x = np.array([1, 0, 0, 0])

In [13]:
# Test whether any of the elements of a given array is non-zero
np.any(x)

True

In [14]:
# Create an array with 1, 0, np.nan, np.inf
x = np.array([1, 0, np.nan, np.inf])

In [15]:
# Test a given array x element-wise for finiteness
np.isfinite(x)

array([ True,  True, False, False])

In [17]:
# Test a given array x elemenet-wise for infinity
np.isinf(x)

array([False, False, False,  True])

In [25]:
x

array([ 1.,  0., nan, inf])

In [18]:
# Test a given array x for NaN
np.isnan(x)

array([False, False,  True, False])

In [20]:
# Create an array with 1+1j, 1+0j, 4.5, 3, 2, 2j
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
a

array([1. +1.j, 1. +0.j, 4.5+0.j, 3. +0.j, 2. +0.j, 0. +2.j])

In [21]:
# Test element-wise of array a is complex number
np.iscomplex(a)

array([ True, False, False, False, False,  True])

In [22]:
# Test element-wise of array a is real number
np.isreal(a)

array([False,  True,  True,  True,  True, False])

In [23]:
# Test element-wise of array a is scalar number
np.isscalar(a)

False

In [24]:
# Test if 3.1 is a scalar number
np.isscalar(3.1)

True

In [27]:
# Create an array x with 3, 5
x = np.array([3,5])

In [28]:
# Create an array y with 2, 5
y = np.array([2,5])

In [29]:
# Compare array x and y with greater function
np.greater(x, y)

array([ True, False])

In [30]:
# Compare array x and y with greater_equal function
np.greater_equal(x, y)

array([ True,  True])

In [31]:
# Compare array x and y with less function
np.less(x, y)

array([False, False])

In [32]:
# Compare array x and y with less_equal function
np.less_equal(x, y)

array([False,  True])

In [33]:
# Create an aray with 1, 7, 13 and 105
x = np.array([1, 7, 13, 105])

In [34]:
# Determine the size of the memory occupied by the array
x.size * x.itemsize

16

In [35]:
# Create an arra of 10 zeros
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
# Create an array of 10 ones
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
# Creat an array of 10 fives
a = np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [38]:
# Create an array from 30 to 70
a = np.arange(30, 71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [40]:
# Create an array of allthe even integers from 30 to 70
a = np.arange(30, 71, 2)
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])