In [1]:
# Import NumPy library
import numpy as np

In [2]:
# Create 5 x 10 Array fo even numbers between 0 and 100
large_array = np.arange(0,100,2).reshape(5,10)
large_array  # show array

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [3]:
# Grab the first item in the array
large_array[0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
# Grab the last item in the array
large_array[-1]

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [6]:
# Grab the last two items
large_array[3:5]

array([[60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])