In [3]:
# Import NumPy package
import numpy as np

# Change the dimensions of an array with reshape()
freq = np.arange(10)   # Create a vector with 10 numbers
freq    # Show array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Make freq 2 dimensional 5 rows, 2 columns
np.reshape(freq, (5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
# Create a vector with 10 random numbers
values = np.random.rand(10)
values 

array([0.54710401, 0.85312031, 0.35550039, 0.20270268, 0.60988223,
       0.77654773, 0.71298315, 0.11602411, 0.36938673, 0.69292941])

In [6]:
# Make values 2 dimensional 2 rows, 5 columns
np.reshape(values, (2,5))

array([[0.60804801, 0.00301779, 0.25453471, 0.46222624, 0.83380153],
       [0.6934672 , 0.17261624, 0.67958446, 0.02491042, 0.79248819]])

In [5]:
# Find the maximum value in the 'values' array
values.max()

0.8531203145148966

In [6]:
# Find the index of the maximum value in the 'values' array
values.argmax()

1

In [7]:
# Find the minimum value in the 'values' array
values.min()

0.11602410972555166

In [8]:
# Find the index of the minimum value in the 'values' array
values.argmin()

7

In [10]:
values

array([0.54710401, 0.85312031, 0.35550039, 0.20270268, 0.60988223,
       0.77654773, 0.71298315, 0.11602411, 0.36938673, 0.69292941])

In [11]:
values[0]  # grabbing 1st item

0.5471040081617016

In [12]:
values[-1]  # grabbing last item

0.6929294145039757

In [13]:
values[1:3]  # grabbing 2nd & 3rd item

array([0.85312031, 0.35550039])

In [14]:
values[3:8]  # item 4 to 8

array([0.20270268, 0.60988223, 0.77654773, 0.71298315, 0.11602411])

In [16]:
# Create a list from 0 to 10
num_list = list(range(11))  # list from 0 to 10
num_list # show list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
list_slice = num_list[:4]  # first 4 items
list_slice     # show slice

[0, 1, 2, 3]

In [18]:
list_slice[:] = [5,7,9,3]   # Re-assignign elements
list_slice    # show updated values

[5, 7, 9, 3]

In [19]:
# Check for the original list
num_list     # show original list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]