In [1]:
import numpy as np

In [2]:
# This is a list of integers
Int_list = [1,2,3,4,5]
Int_list

[1, 2, 3, 4, 5]

In [3]:
# Create an array of integers
x = np.array(Int_list)
x

array([1, 2, 3, 4, 5])

In [4]:
# Check for the type of array
type(x)

numpy.ndarray

In [5]:
# Shows how many dimensions the array has
x.ndim

1

In [6]:
# Shows the shape (the arrangement)
x.shape

(5,)

In [7]:
# This is a matrix
x = [1,2,3]
y = [4,5,6]
my_list = [y,x]  # nested list
my_matrix = np.array(my_list)  # creating the matrix
my_matrix   # show the matrix

array([[4, 5, 6],
       [1, 2, 3]])

In [8]:
# Show the dimensions
my_matrix.ndim

2

In [10]:
# Show the shape (the arrangement)
my_matrix.shape

(2, 3)

In [11]:
my_matrix

array([[4, 5, 6],
       [1, 2, 3]])

In [13]:
# Transpose the matrix (change the rows to columns)
t_matrix = my_matrix.transpose()
t_matrix  # show the new matrix

array([[4, 1],
       [5, 2],
       [6, 3]])

In [14]:
# Array of even numbers between 0 and 10
Even_array = np.arange(0,11,2)
Even_array   # show the even number array

array([ 0,  2,  4,  6,  8, 10])

In [15]:
# Array of even floating numbers between 0 and 10
Even_array2 = np.arange(0,11,2,dtype='float')
Even_array2   # show the even floating number array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [17]:
# Arrays of linearly spaced points
A = np.linspace(0,5,5)   # 5 equal pionts between 0 & 5
A  # show Array A

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [18]:
B = np.linspace(51,100)  # 50 equal points between 51 & 100
B  # show Array B

array([ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.,
        62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
        73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
        84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,
        95.,  96.,  97.,  98.,  99., 100.])

In [21]:
# Create a vector of 3 elements with zeros()
np.zeros(3)    # A vector of 3 elements

array([0., 0., 0.])

In [22]:
# Create a matrix of 6 elements: 2 rows, 3 columns
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# Create a vector of 3 elements with ones()
np.ones(3)      # A vector of 3 elememnts

array([1., 1., 1.])

In [24]:
# Create a matrix of 6 elements with ones()
np.ones((2,3))   # A matrix of 6 elements: 2 rows, 3 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# Create a vector 2 random values
np.random.rand(2)   # A vector of 2 random values

array([0.91288399, 0.73833748])

In [26]:
# Create a matrix of 6 random values
np.random.rand(2,3)  # A matrix of 6 random values

array([[0.12337406, 0.66803363, 0.6819524 ],
       [0.16347317, 0.48674082, 0.61252924]])

In [27]:
# Create a random value between 1 and 5
np.random.randint(1,5)    # A random value between 1 and 5

2

In [28]:
# Create a vector of 6 random values between 1 and 100
np.random.randint(1,100,6)

array([ 4, 28, 85, 56, 93, 52])

In [29]:
# Create a matrix of 6 random values between 1 and 100
np.random.randint(1,100,(2,3))

array([[38, 64, 56],
       [28, 87,  4]])

In [30]:
# Create a dice roll game with randinit()
# Define the function
def roll_dice():
    #This function displays a dice roll value when called
    dice1 = np.random.randint(1,7)  # This allows 6 to be inclusive
    dice2 = np.random.randint(1,7)  
    
    # Display condition
    if dice1 == dice2:
        print('Roll: ', dice1, '&', dice2,'\ndoubles!')
    if dice1 == 1:
        print('snake eyes')
    else:
        print('Roll: ', dice1, '&', dice2)

In [35]:
# Call the function
roll_dice()

Roll:  6 & 6 
doubles!
Roll:  6 & 6
