In [3]:
# Import NumPy package
import numpy as np

# Change the dimensions of an array with reshape()
freq = np.arange(10)   # Create a vector with 10 numbers
freq    # Show array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Make freq 2 dimensional 5 rows, 2 columns
np.reshape(freq, (5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
# Create a vector with 10 random numbers
values = np.random.rand(10)
values 

array([0.54710401, 0.85312031, 0.35550039, 0.20270268, 0.60988223,
       0.77654773, 0.71298315, 0.11602411, 0.36938673, 0.69292941])

In [6]:
# Make values 2 dimensional 2 rows, 5 columns
np.reshape(values, (2,5))

array([[0.60804801, 0.00301779, 0.25453471, 0.46222624, 0.83380153],
       [0.6934672 , 0.17261624, 0.67958446, 0.02491042, 0.79248819]])

In [5]:
# Find the maximum value in the 'values' array
values.max()

0.8531203145148966

In [6]:
# Find the index of the maximum value in the 'values' array
values.argmax()

1

In [7]:
# Find the minimum value in the 'values' array
values.min()

0.11602410972555166

In [8]:
# Find the index of the minimum value in the 'values' array
values.argmin()

7

In [10]:
values

array([0.54710401, 0.85312031, 0.35550039, 0.20270268, 0.60988223,
       0.77654773, 0.71298315, 0.11602411, 0.36938673, 0.69292941])

In [11]:
values[0]  # grabbing 1st item

0.5471040081617016

In [12]:
values[-1]  # grabbing last item

0.6929294145039757

In [13]:
values[1:3]  # grabbing 2nd & 3rd item

array([0.85312031, 0.35550039])

In [14]:
values[3:8]  # item 4 to 8

array([0.20270268, 0.60988223, 0.77654773, 0.71298315, 0.11602411])

In [16]:
# Create a list from 0 to 10
num_list = list(range(11))  # list from 0 to 10
num_list # show list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
list_slice = num_list[:4]  # first 4 items
list_slice     # show slice

[0, 1, 2, 3]

In [18]:
list_slice[:] = [5,7,9,3]   # Re-assignign elements
list_slice    # show updated values

[5, 7, 9, 3]

In [19]:
# Check for the original list
num_list     # show original list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
# Slice first 4 items in the list
list_slice = num_list[:4]      # first 4 items
list_slice      # show slice

[0, 1, 2, 3]

In [21]:
# Create an array from 0 to 10
num_array = np.arange(11)       # array from 0-10
num_array       # show array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Slice first 4 items in the array
array_slice = num_array[:4]     # first 4 items
array_slice      # show slice

array([0, 1, 2, 3])

In [23]:
# Re-assign elements
array_slice[:] = [5,7,9,3]   # Re-assign elements
array_slice     # show slice

array([5, 7, 9, 3])

In [24]:
# Check for the original array
num_array    # show original array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Make a copy of the first 4 items of the original array
array_copy = num_array.copy()[:4]   # copies the first 4 items of the array 
array_copy   # show array

array([5, 7, 9, 3])

In [26]:
# Re-assign 10 to the copied array
array_copy[:] = 10     # re-assign 10 to the copied array
array_copy     # show array

array([10, 10, 10, 10])

In [27]:
# Check the original array
num_array   # show the original array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Create the matrix
matrix = np.array(([5,10,15],[20,25,30],[35,40,45]))
matrix     # display matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
# Grab the second row
matrix[1]

array([20, 25, 30])

In [30]:
# Grab 35
matrix[2][0]

35

In [31]:
# Grab first 2 rows
matrix[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
# Grab 45
matrix[2,2]

45

In [33]:
# Grab the second column
column_slice = matrix[:,1:2]    # Assign the second column to a variable
column_slice

array([[10],
       [25],
       [40]])