In [1]:
import numpy as np
np.set_printoptions(precision=2)

In [2]:
print(np.__version__)

1.16.5


In [3]:
my_array = np.array(np.arange(10))
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
my_array * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
my_array = np.zeros(20)
my_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [8]:
my_array[0::5] = 4
my_array

array([4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0.,
       0., 0., 0.])

In [9]:
my_matrix = np.asmatrix(np.array(np.arange(9)).reshape((3,3)))
my_matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [10]:
my_matrix.T

matrix([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [11]:
my_matrix = np.asmatrix(np.eye(5, dtype='int'))
my_matrix

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [12]:
my_random_vector = np.random.random(30)
my_random_vector

array([0.55, 0.89, 0.04, 0.53, 0.32, 0.11, 0.66, 0.52, 0.92, 0.13, 0.88,
       0.93, 0.24, 0.73, 0.89, 0.27, 0.93, 0.84, 0.84, 0.97, 0.81, 0.13,
       0.76, 0.63, 0.16, 0.93, 0.67, 0.08, 0.72, 0.33])

In [13]:
my_random_vector.mean()

0.5805771110177561

In [14]:
my_bordered_array = np.ones((5,5))
my_bordered_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
my_bordered_array[1:-1, 1:-1] = 0
my_bordered_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
my_checker_board = np.zeros((8,8), dtype=int)
my_checker_board

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
my_checker_board[1::2, ::2] = 1
my_checker_board[::2, 1::2] = 1
my_checker_board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [18]:
my_alternative_checker_board = np.tile(np.array([[0,1],[1,0]]), (4, 4))
my_alternative_checker_board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [19]:
vector_size = 12
my_random_vector = np.random.random(vector_size)
my_sorted_random_vector = np.sort(my_random_vector)
my_sorted_random_vector

array([0.06, 0.15, 0.19, 0.22, 0.41, 0.5 , 0.66, 0.67, 0.68, 0.89, 0.96,
       0.99])

In [20]:
my_random_vector[my_random_vector.argmax()] = 1234
my_random_vector

array([4.99e-01, 5.98e-02, 6.77e-01, 4.06e-01, 6.65e-01, 9.56e-01,
       1.47e-01, 2.24e-01, 8.90e-01, 6.56e-01, 1.94e-01, 1.23e+03])

In [21]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [22]:
camelot_structured_array = np.array(camelot_values, dtype=camelot_dtype)
camelot_sorted_array = np.sort(camelot_structured_array, order='height')
for n in np.arange(camelot_sorted_array.size):
    print (camelot_sorted_array[n])

(b'Galahad', 1.7, 38)
(b'Arthur', 1.8, 41)
(b'Lancelot', 1.9, 38)
