## 3.1. Sorting NumPy Arrays 

### 3.1.1. Soring Numeric Arrays

In [38]:
import numpy as np

print("unsorted array")
my_array = np.random.randint(1,20,10)
print(my_array)

print("\nsorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
[ 3 17  8  6 10  8 15 13 18  5]

sorted array
[ 3  5  6  8  8 10 13 15 17 18]


### 3.1.2. Sorting Text Arrays

In [39]:
import numpy as np

print("unsorted array")
my_array = np.array(["Red", "Green", "Blue", "Yello"])
print(my_array)

print("\nsorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
['Red' 'Green' 'Blue' 'Yello']

sorted array
['Blue' 'Green' 'Red' 'Yello']


### 3.1.3. Sorting Boolean Arrays

In [4]:
import numpy as np

print("unsorted array")
my_array = np.array([False, True, True, False, False, True, False, True])
print(my_array)

print("\nSorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
[False  True  True False False  True False  True]

Sorted array
[False False False False  True  True  True  True]


### 3.1.4. Sorting 2-D Arrays

In [5]:
import numpy as np

print("unsorted array")
my_array = np.random.randint(1,20, size = (4,6))
print(my_array)

print("Sorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
[[19  3 12  1  2 12]
 [ 7  1 15 13 19  8]
 [15 10 16  7 18  4]
 [19 16  1  2  5 10]]
Sorted array
[[ 1  2  3 12 12 19]
 [ 1  7  8 13 15 19]
 [ 4  7 10 15 16 18]
 [ 1  2  5 10 16 19]]


### 3.1.5. Sorting in Descending Order

In [6]:
import numpy as np

print("unsorted array")
my_array = np.random.randint(1,20,10)
print(my_array)

print("\nsorted array")
sorted_array = np.sort(my_array)
reverse_sorted = np.flipud(sorted_array)
print(reverse_sorted)

unsorted array
[ 8  6  9 10  7 15 17  6 10 16]

sorted array
[17 16 15 10 10  9  8  7  6  6]


## 3.2. Reshaping NumPy Arrays

### 3.2.1. Reshaping from Lower to Higher Dimensions

In [7]:
import numpy as np

print("one-dimensional array")
one_d_array = np.random.randint(1,20,10)
print(one_d_array)

print("\ntwo-dimensional array")
two_d_array = one_d_array.reshape(2,5)
print(two_d_array)

one-dimensional array
[ 5  3  2  4  9  2 17  2 14  9]

two-dimensional array
[[ 5  3  2  4  9]
 [ 2 17  2 14  9]]


In [8]:
import numpy as np

print("one-dimensional array")
one_d_array = np.random.randint(1,20,10)
print(one_d_array)

print("\ntwo-dimensional array")
two_d_array = np.reshape(one_d_array,(2,5))
print(two_d_array)

one-dimensional array
[ 8  9  9 13 11 11  8  1 13 10]

two-dimensional array
[[ 8  9  9 13 11]
 [11  8  1 13 10]]


In [9]:
import numpy as np

print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(one_d_array)

print("\nthree-dimensional array")
three_d_array = np.reshape(two_d_array,(3,4,2))
print(two_d_array)

two-dimensional array
[ 8  9  9 13 11 11  8  1 13 10]

three-dimensional array
[[ 6 14 19 18 15  5]
 [18 10 10  5  4 16]
 [11 12  8 17 13  7]
 [ 9 11 15 12  6 13]]


In [10]:
import numpy as np

print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(one_d_array)

print("\nthree-dimensional array")
three_d_array = np.reshape(two_d_array,(1,4,2))
print(two_d_array)

two-dimensional array
[ 8  9  9 13 11 11  8  1 13 10]

three-dimensional array


ValueError: cannot reshape array of size 24 into shape (1,4,2)

### 3.2.2. Reshaping Higher Dimensions To Lower Dimensions

In [11]:
import numpy as np

print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(two_d_array)

print("\none-dimensional array")
one_d_array = two_d_array.reshape(24)
print(one_d_array)

two-dimensional array
[[ 2 11  7  3 10 12]
 [ 1 14 16  4  7  3]
 [12 17  3  8  5  6]
 [10  9 15  6  5  2]]

one-dimensional array
[ 2 11  7  3 10 12  1 14 16  4  7  3 12 17  3  8  5  6 10  9 15  6  5  2]


In [12]:
import numpy as np

print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(two_d_array)

print("\none-dimensional array")
one_d_array = two_d_array.reshape(-1)
print(one_d_array)

two-dimensional array
[[ 9 16 12  7 11  1]
 [15  7 14  5  6  7]
 [12  3  4 13  7  3]
 [18  3 14  2 18 16]]

one-dimensional array
[ 9 16 12  7 11  1 15  7 14  5  6  7 12  3  4 13  7  3 18  3 14  2 18 16]


In [13]:
import numpy as np

print("two-dimensional array")
three_d_array = np.random.randint(1,20, size = (4,2,6))
print(three_d_array )

print("\non-dimensional array")
one_d_array = three_d_array .reshape(-1)
print(one_d_array)

two-dimensional array
[[[ 7 15  5  8  1 13]
  [10  8 17 19 15 13]]

 [[ 8 15 16  6  1  3]
  [19  9 15  8  5 13]]

 [[ 6  1  7 15 16 11]
  [ 5  7  8  1  7  1]]

 [[15  6 19  3 13  8]
  [10  3  8 10  3  9]]]

on-dimensional array
[ 7 15  5  8  1 13 10  8 17 19 15 13  8 15 16  6  1  3 19  9 15  8  5 13
  6  1  7 15 16 11  5  7  8  1  7  1 15  6 19  3 13  8 10  3  8 10  3  9]


## 3.3. Array Indexing and Slicing

In [14]:
import numpy as np
s = np.arange(1,11)  
print(s) 


[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
print(s[1])  

2


In [16]:
print(s[1:9])  

[2 3 4 5 6 7 8 9]


In [17]:
print(s[:5])  
print(s[5:])  

[1 2 3 4 5]
[ 6  7  8  9 10]


In [18]:
row1 = [10,12,13]  
row2 = [45,32,16]  
row3 = [45,32,16]  
  
nums_2d = np.array([row1, row2, row3])  
print(nums_2d[:2,:])   

[[10 12 13]
 [45 32 16]]


In [19]:
row1 = [10,12,13]  
row2 = [45,32,16]  
row3 = [45,32,16]  
 
nums_2d = np.array([row1, row2, row3])  

print(nums_2d[:,:2])   

[[10 12]
 [45 32]
 [45 32]]


In [20]:
row1 = [10,12,13]  
row2 = [45,32,16]  
row3 = [45,32,16]  
 
nums_2d = np.array([row1, row2, row3])  
print(nums_2d[1:,1:]) 


[[32 16]
 [32 16]]


## 3.4. Broadcasting NumPy Arrays

In [21]:
import numpy as np

array1 = np.array ([14,25,31])
array2 = np.array([10])
result = array1 + array2 
print(result)

[24 35 41]


In [22]:

array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([10])

print("after bradcasting")
result = array1 + array2 
print(result)

[[14  5 10  1]
 [18 18  1  2]
 [13  4 17  5]]
after bradcasting
[[24 15 20 11]
 [28 28 11 12]
 [23 14 27 15]]


In [23]:

array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([5,10,20,25])

print("after bradcasting")
result = array1 + array2 
print(result)

[[ 8  7 16  3]
 [ 2 18 12 13]
 [ 2 19 17  7]]
after bradcasting
[[13 17 36 28]
 [ 7 28 32 38]
 [ 7 29 37 32]]


In [24]:
array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([[5],[10],[20]])

print("after bradcasting")
result = array1 + array2 
print(result)

[[15 10 18  3]
 [ 1 11  4 12]
 [ 1 16  2  9]]
after bradcasting
[[20 15 23  8]
 [11 21 14 22]
 [21 36 22 29]]


## 3.5. Copying NumPy Arrays

In [25]:
import numpy as np
array1 = np.array([10,12,14,16,18,20])

array2 = array1.copy()
array2[1] = 20

print(array1)
print(array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]


In [26]:
array1 = np.array([10,12,14,16,18,20])

array2 = np.copy(array1)
array2[1] = 20

print(array1)
print(array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]


In [27]:
array1 = np.array([10,12,14,16,18,20])

array2 = array1.view()
array2[1] = 20

print(array1)
print(array2)

[10 20 14 16 18 20]
[10 20 14 16 18 20]


## 3.6. NumPy I/O Operations

### 3.6.1. Saving a NumPy Array

In [33]:
import numpy as np
array1 = np.array([10,12,14,16,18,20])

np.save("c:/temp/my_array", array1)

In [34]:
import numpy as np
array1 = np.array([10,12,14,16,18,20])

np.savetxt("c:/temp/my_array.txt", array1)

### 3.6.2. Loading a NumPy Array

In [35]:
import numpy as np
loaded_array = np.load("c:/temp/my_array.npy")
print(loaded_array)

[10 12 14 16 18 20]


In [36]:
import numpy as np
loaded_array = np.loadtxt("c:/temp/my_array.txt")
print(loaded_array)

[10. 12. 14. 16. 18. 20.]


## Exercise 3.1


**Question 1:**

Which function is used to convert a multi-dimensional NumPy array into a flat array of 1-dimension?

A- np.reshape(0)

B- np.reshape(-1)

C- np.reshape(1)

D- None of the Above

Answer: B


**Question 2:**

Which function is used to save a NumPy array in text format?

A- np.savetext()

B- np.saveText()

C- np.saveTxt()

D- np.savetxt()

Answer: D


**Question 3:**

To sort a NumPy array in descending order, you can use the following function:

A- np.flipud(np.sort(my_array))

B- np.sort(np.flip(my_array))

C- np.sort()

D- np.flip()

Answer: A

## Exercise 3.2

Create a random NumPy array of 4 rows and 5 columns. Using array indexing and slicing, display the items from row 3 to end and column 2 to end.

**Solution:**

In [37]:
uniform_random = np.random.rand(4, 5)
print(uniform_random)
print("Result")
print(uniform_random[2:,1:])

[[0.22274888 0.94708108 0.91456799 0.10947778 0.11966606]
 [0.28615944 0.5837256  0.83659242 0.56185408 0.95183326]
 [0.08608761 0.79592315 0.26014112 0.14017445 0.31678948]
 [0.20683328 0.82228997 0.80852221 0.37544098 0.81976294]]
Result
[[0.79592315 0.26014112 0.14017445 0.31678948]
 [0.82228997 0.80852221 0.37544098 0.81976294]]
