In [1]:
import numpy as np

In [2]:
days = 30

In [3]:
high_temps = np.random.uniform(20, 35, size=days)
high_temps

array([23.67384542, 20.00599634, 26.65857302, 26.61526863, 25.75800668,
       26.56405945, 26.56231537, 29.16621802, 26.32649422, 32.50116162,
       20.51527282, 24.77607868, 29.35618341, 21.40540524, 23.36583574,
       23.64826134, 30.42628055, 21.54692698, 23.37050282, 33.30965283,
       32.09912626, 31.43966258, 33.32265757, 30.55658685, 29.07466565,
       32.96306789, 25.53449485, 26.79969981, 22.23986848, 26.38367772])

In [4]:
low_temps = np.random.uniform(10, 25, size=days)
low_temps

array([22.30131666, 16.47465455, 11.88379306, 10.8426915 , 21.46376808,
       16.84566557, 16.58837585, 11.86359385, 16.37200702, 17.3631263 ,
       15.45833282, 19.17166627, 12.36810912, 20.59165928, 16.73998875,
       23.5019508 , 12.08565834, 24.46285583, 24.32785951, 12.83049497,
       19.50007703, 23.31151791, 17.12544969, 18.94696913, 18.54787767,
       20.96715797, 12.2915267 , 12.51406628, 23.61074427, 13.44694682])

In [5]:
precipitation = np.random.choice([0, 0, 0, 10, 20, 30], size=days)
precipitation

array([30, 20, 20,  0,  0,  0,  0,  0, 10,  0, 20,  0, 30, 30, 10, 20, 20,
        0, 30, 30,  0,  0, 10, 30,  0,  0,  0,  0,  0, 10])

In [6]:
weather_data = np.column_stack((high_temps, low_temps, precipitation))
weather_data

array([[23.67384542, 22.30131666, 30.        ],
       [20.00599634, 16.47465455, 20.        ],
       [26.65857302, 11.88379306, 20.        ],
       [26.61526863, 10.8426915 ,  0.        ],
       [25.75800668, 21.46376808,  0.        ],
       [26.56405945, 16.84566557,  0.        ],
       [26.56231537, 16.58837585,  0.        ],
       [29.16621802, 11.86359385,  0.        ],
       [26.32649422, 16.37200702, 10.        ],
       [32.50116162, 17.3631263 ,  0.        ],
       [20.51527282, 15.45833282, 20.        ],
       [24.77607868, 19.17166627,  0.        ],
       [29.35618341, 12.36810912, 30.        ],
       [21.40540524, 20.59165928, 30.        ],
       [23.36583574, 16.73998875, 10.        ],
       [23.64826134, 23.5019508 , 20.        ],
       [30.42628055, 12.08565834, 20.        ],
       [21.54692698, 24.46285583,  0.        ],
       [23.37050282, 24.32785951, 30.        ],
       [33.30965283, 12.83049497, 30.        ],
       [32.09912626, 19.50007703,  0.   

In [7]:
mean_high = np.mean(weather_data[:, 0])
mean_low = np.mean(weather_data[:, 1])
total_rain = np.sum(weather_data[:, 2])

print(mean_high)

26.86552822810003


In [8]:
print(mean_low)

17.459996720433825


In [9]:
print(total_rain)

320.0
